default: 
  just -l
  
# assemble debug
ad: 
  gradle assembleDebug

# assemble debug
ar: 
  gradle assembleRelease

# task list
tl: 
  gradle tasks 

# list app composeApp tasks
tla:
  gradle :labor-app:composeApp:tasks

# task run app {{taskName}}
tra taskName:
  gradle :labor-app:composeApp:{{taskName}}

# pair then connect
# pair, usage: pair 192.168.1.7 40259 052330
p address port pairCode: 
  adb pair {{address}}:{{port}} {{pairCode}}

# connect, usage: 192.168.1.7:40259
c address:
  adb connect {{address}}

# list devices
ld: 
  adb devices

# install device continuous
idc: 
    gradle installDebug --continuous

# install debug
id: 
  gradle installDebug 
